from datetime import date
from typing import Protocol

from app.models import Appointment, AppointmentSlot, Customer, Device, Handover, Ticket


class CustomerRepository(Protocol):
    async def get(self, customer_id: str) -> Customer | None: ...


class DeviceRepository(Protocol):
    async def get(self, device_id: str) -> Device | None: ...
    async def list_for_customer(self, customer_id: str) -> list[Device]: ...


class TicketRepository(Protocol):
    async def get(self, ticket_id: str) -> Ticket | None: ...
    async def list_for_customer(self, customer_id: str) -> list[Ticket]: ...
    async def find_active(self, customer_id: str, device_id: str, problem_code: str) -> Ticket | None: ...
    async def add(self, ticket: Ticket) -> Ticket: ...


class AppointmentRepository(Protocol):
    async def get(self, appointment_id: str) -> Appointment | None: ...
    async def get_slot(self, slot_id: str) -> AppointmentSlot | None: ...
    async def list_for_customer(self, customer_id: str) -> list[Appointment]: ...
    async def list_available_slots(self, from_date: date, to_date: date) -> list[AppointmentSlot]: ...
    async def reschedule(self, appointment_id: str, slot_id: str) -> Appointment | None: ...


class HandoverRepository(Protocol):
    async def get(self, handover_id: str) -> Handover | None: ...
    async def add(self, handover: Handover) -> Handover: ...
